export const ICON ={
    TOTAL_MONEY:'icon/total-money.png',
    DEBT:'icon/debt.png',
    EXIT:'icon/uiIcon/exit.png',
    EXIT_MAN:'icon/uiIcon/exit-man.png',
    X_MARK:'icon/uiIcon/xMark.png',
    SEARCH:'icon/search.png',
    EVENTS_NO:'icon/noEvents.png',
    HOUSE:'icon/uiIcon/house.png',
    CLEAR:'icon/uiIcon/clear.png',
    STATISTIC:'icon/uiIcon/statistic.png',
    HANDCUFFS:'icon/handcuffs.png',
    PRISON:'icon/prison.png',
    DOOR:'icon/uiIcon/door.png',
    WINDOW:'icon/uiIcon/window.png',
    GARAGE:'icon/uiIcon/garage.png',
    BACK:'icon/uiIcon/back.png',
    INVENTORY:'icon/inventory.png',
    INVENTORY_WHITE:'icon/inventory-white.png',
    SAFE:'icon/uiIcon/safe.png',
    CHECK_MARK:'icon/check-mark.png',
    PAY:'icon/pay.png',
    SELL:'icon/sell.png',
    MAN2:'icon/man-2.png',
    MAN3:'icon/man-3.png',
    ENERGY:'icon/energy.png',
    GARBAGE:'icon/uiIcon/garbage.png',
}

export const EVENTS_ICON = {
    PHLASHER:'icon/flasher.png',
    MORE_MONEY:'icon/icons-of-valuables/more-money.png',
    OPEN_DOOR:'icon/openDoor.png',
    PARTY:'icon/party.png'
}